export const GET_TRENDING = "GET_TRENDING";

export const SET_ITEM_TYPE_MOVIE = "SET_ITEM_TYPE_MOVIE";
export const SET_ITEM_TYPE_TV = "SET_ITEM_TYPE_TV";

export const GET_MOVIES_FROM_BUTTON = "GET_MOVIES_FROM_BUTTON";

export const GET_MOVIES_NOWPLAYING = "GET_MOVIES_NOWPLAYING";
export const GET_MOVIES_POPULAR = "GET_MOVIES_POPULAR";
export const GET_MOVIES_TOP_RATED = "GET_MOVIES_TOP_RATED";
export const GET_MOVIES_UPCOMING = "GET_MOVIES_UPCOMING";
export const GET_MOVIE_DETAILS = "GET_MOVIE_DETAILS";
export const GET_MOVIE_CREDITS = "GET_MOVIE_CREDITS";
export const GET_MOVIE_TRAILERS = "GET_MOVIE_TRAILERS";
export const GET_MOVIE_REVIEWS = "GET_MOVIE_REVIEWS";

export const GET_TV_AIRING_TODAY = "GET_TV_AIRING_TODAY";
export const GET_TV_POPULAR = "GET_TV_POPULAR";
export const GET_TV_ON_THE_AIR = "GET_TV_ON_THE_AIR";
export const GET_TV_TOP_RATED = "GET_TV_TOP_RATED";
export const GET_TV_DETAILS = "GET_TV_DETAILS";
export const GET_TV_CREDITS = "GET_TV_CREDITS";
export const GET_TV_TRAILERS = "GET_TV_TRAILERS";
export const GET_TV_REVIEWS = "GET_TV_REVIEWS";

export const GET_PEOPLE_DETAILS = "GET_PEOPLE_DETAILS";
export const GET_PEOPLE_COMBINED_CREDITS = "GET_PEOPLE_COMBINED_CREDITS";
export const GET_PEOPLE_PHOTOS = "GET_PEOPLE_PHOTOS";
export const CONFIG_DATA = "CONFIG_DATA";
export const TOGGLE_NAV = "TOGGLE_NAV";
export const SEARCH_MOVIES = "SEARCH_MOVIES";
export const POST_SEARCH_RESULTS = "POST_SEARCH_RESULTS";

export const GET_DISCOVER = "GET_DISCOVER";
